library(shiny)

shinyUI(fluidPage(
  tags$head(tags$script(src="format_numbers.js")),
  
  h4("Option 1"),
  "Leave the number of the box unchanged and format it when you ",
  "refer to it. This lets you keep the arrows' functionality and ",
  "not worry about having commas in the middle of your number ",
  "when you use ", HTML("<code>inpu$n</code>"), "later on. ",
  "Also, you don't need any Javascript to do this!",
  br(),
  br(),
  numericInput('n1', 'Enter a number', 5000),
  "Here's your value as is:",
  textOutput('numberN1', inline = TRUE),
  ". It's already a number, so no need to perform extra things to ",
  "use it in numeric operations. Your number times 2 is: ",
  textOutput('numberN1op', inline = TRUE),
  br(),
  "Here's your nicely formatted number:",
  textOutput('formatN1', inline = TRUE),
  hr(),
  h4("Option 2"),
  "Format the number in the box itself. If you do this, you lose ",
  "some functionality (the box arrows and the ability to use the ",
  "keyboard arrows when editing the number -- you always need to ",
  "use the mouse). You'll also need to convert the input back ",
  "into a comma-less number when you want to use it later on to",
  "perform numeric operations.",
  br(),
  br(),
  numericInput('n2', 'Enter a number', 5000),
  "Here's your value as is:",
  textOutput('formatN2', inline = TRUE),
  br(),
  "If you want to use it as a number, it requires some manipulation: ",
  textOutput('numberN2', inline = TRUE),
  ". You can now use it in numeric operations; your number times 2 is: ",
  textOutput('numberN2op', inline = TRUE)
))